language: generic
sudo: required
dist: trusty
cache:
  directories:	
    - bin/CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
            - libgtest-dev
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc -f
script:
  - mkdir bin && cd bin
  - cmake .. -Wno-dev
  - make
  - cd ..
