language: generic
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libgtest-dev
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
install:
script:
  - mkdir bin && cd ./bin 
  - cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ./CarbonTests
  - cd ..
  
