language: generic
sudo: required
dist: trusty
cache:
  directories:
    - googletest	
    - bin/CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
script:
  - cd bin
  - cmake .. -Wno-dev
  - cmake --build . -- -j 4
  - cd ..
