language: generic
sudo: required
dist: trusty
cache:
  directories:
    - googletest	
    - bin/CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc -f
  - |
    if [ ! -f ./googletest/cached_mark ];
    then
    git clone https://github.com/google/googletest --depth=1
    cd ./googletest
    cmake . -DCMAKE_BUILD_TYPE=Release
    make
    touch cached_mark
    cd ..
    fi
  - cd ./googletest
  - sudo make install
script:
  - cd bin
  - cmake .. -Wno-dev
  - make
  - cd ..
