#include "Carbon/System/IO/IOBase/BinaryIOStreamBase.hpp"

namespace Carbon {
#define CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(type) IBStream & operator<<(IBStream &in, type var) {\
    in.read(reinterpret_cast<Carbon::Byte*>(&var), sizeof(type)); return in; }
#define CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(type) OBStream & operator>>(OBStream &out, type& var) {\
    out.write(reinterpret_cast<Carbon::Byte*>(&var), sizeof(type)); return out; }
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(char)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(short)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(int)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(long long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(unsigned char)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(unsigned short)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(unsigned int)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(unsigned long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION(unsigned long long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(char)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(short)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(int)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(long long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(unsigned char)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(unsigned short)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(unsigned int)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(unsigned long)
    CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION(unsigned long long)
#undef CARBON_BINARYIOSTREAMBASE_OPERATOR_READ_EXPANSION
#undef CARBON_BINARYIOSTREAMBASE_OPERATOR_WRITE_EXPANSION
}
